const siteConfig = { whatsapp: "5571983202118", whatsappMessage: "Olá! Vim pelo site da Lamarc Tech e gostaria de conversar sobre uma solução para minha empresa.", instagram: "" /* Pendente: preencher somente quando o perfil empresarial real for confirmado. */ };
const services = [
  { icon:"AI",title:"IA e automação",problem:"Atendimento e tarefas manuais consomem a equipe.",solution:"Chatbots, triagem de contatos, assistentes virtuais, notificações e integrações entre ferramentas.",benefit:"Mais organização, agilidade e produtividade, com aplicação prática de IA." },
  { icon:"WEB",title:"Sites e presença digital",problem:"A empresa não tem um canal próprio que transmita confiança.",solution:"Sites empresariais, landing pages, portfólios, catálogos e páginas para campanhas, integrados aos seus canais.",benefit:"Uma presença profissional, responsiva e preparada para gerar novas oportunidades." },
  { icon:"SYS",title:"Sistemas sob medida",problem:"Planilhas e processos improvisados limitam a operação.",solution:"Sistemas web, painéis, dashboards, APIs e ferramentas internas adaptadas ao fluxo do negócio.",benefit:"Informação centralizada, menos trabalho manual e uma operação pronta para evoluir." },
  { icon:"MAP",title:"Consultoria e estrutura digital",problem:"Há muitas ferramentas, mas falta um plano conectado.",solution:"Diagnóstico de processos, planejamento digital e estrutura tecnológica para atendimento, leads e campanhas.",benefit:"Decisões mais claras e investimento direcionado ao que realmente gera valor." }
];
const projects = [
  {title:"HardApply",segment:"Produto digital",type:"Em breve",text:"Sistema para organizar candidaturas, entrevistas, currículos e notificações, reunindo front-end, back-end, autenticação, banco de dados e automações.",image:"assets/projects/em-breve.png",link:""},
  {title:"MV Eletrodiesel",segment:"Serviços automotivos",type:"Em breve",text:"Site empresarial para apresentar serviços de injeção diesel, experiência, localização e contato para orçamento.",image:"assets/projects/em-breve.png",link:""},
  {title:"Luiz Envelopamento",segment:"Envelopamento",type:"Projeto realizado",text:"Site e portfólio comercial para destacar trabalhos, áreas atendidas e facilitar o contato com a empresa.",image:"assets/projects/luiz-envelopamento-hero.png",link:"https://luizenvelopamento.com.br/",external:true},
  {title:"Jessik Turismo",segment:"Turismo",type:"Protótipo",text:"Presença digital para apresentar serviços, destinos e facilitar o contato, como alternativa completa ao Linktree.",image:"prototipos/jessikturismo/assets/hero-jessik-turismo.webp",link:"prototipos/jessikturismo/index.html"},
  {title:"Refrigeração e climatização",segment:"Serviços técnicos",type:"Protótipo",text:"Página comercial para instalação, manutenção e assistência técnica de ar-condicionado.",image:"prototipos/refrigeracao/assets/tecnico-split.svg",link:"prototipos/refrigeracao/index.html"},
  {title:"Escolas e cursos",segment:"Educação",type:"Protótipo",text:"Experiência digital para apresentar cursos, metodologia e equipe, com caminho claro para novas matrículas.",image:"prototipos/escola-idiomas/assets/hero-students.svg",link:"prototipos/escola-idiomas/index.html"},
  {title:"Projeto social",segment:"Esporte e comunidade",type:"Protótipo",text:"Site para comunicar uma causa, aproximar participantes e abrir caminhos para apoio, voluntariado e parcerias.",image:"prototipos/projeto-social/assets/logo-karate-social.jpeg",link:"prototipos/projeto-social/index.html"},
  {title:"Comunicação política",segment:"Comunicação pública",type:"Protótipo",text:"Conceito de presença digital para apresentar trajetória, propostas e canais de participação.",image:"prototipos/politico/assets/candidato.svg",link:"prototipos/politico/index.html"}
];
const whatsappUrl=`https://wa.me/${siteConfig.whatsapp}?text=${encodeURIComponent(siteConfig.whatsappMessage)}`;
document.querySelectorAll("[data-whatsapp]").forEach(link=>{link.href=whatsappUrl;link.target="_blank";link.rel="noopener noreferrer"});
document.querySelector("[data-services]").innerHTML=services.map(item=>`<article class="service-card reveal"><span class="card-icon">${item.icon}</span><h3>${item.title}</h3><p><strong>O desafio</strong>${item.problem}</p><p><strong>A solução</strong>${item.solution}</p><p class="benefit">${item.benefit}</p><a href="${whatsappUrl}" target="_blank" rel="noopener noreferrer">Conversar sobre esta solução <span>↗</span></a></article>`).join("");
document.querySelector("[data-projects]").innerHTML=projects.map(item=>{const blankAttrs=' target="_blank" rel="noopener noreferrer"';const image=`<img src="${item.image}" alt="Prévia do ${item.type.toLowerCase()} ${item.title}" loading="lazy" width="720" height="480">`;const media=item.image?(item.link?`<a class="project-image" href="${item.link}"${blankAttrs}>${image}</a>`:`<div class="project-image">${image}</div>`):`<div class="project-image project-placeholder" aria-hidden="true"><span>LT</span><strong>${item.segment}</strong></div>`;const action=item.link?`<a href="${item.link}"${blankAttrs}>Ver projeto <span>→</span></a>`:`<span class="project-no-link">Em breve</span>`;return `<article class="project-card reveal">${media}<div class="project-body"><div class="project-meta"><span>${item.type}</span><span>${item.segment}</span></div><h3>${item.title}</h3><p>${item.text}</p>${action}</div></article>`}).join("");
document.querySelector("[data-year]").textContent=new Date().getFullYear();
const toggle=document.querySelector(".menu-toggle"),nav=document.querySelector(".nav");toggle.addEventListener("click",()=>{const open=toggle.getAttribute("aria-expanded")==="true";toggle.setAttribute("aria-expanded",String(!open));nav.classList.toggle("is-open",!open)});nav.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{nav.classList.remove("is-open");toggle.setAttribute("aria-expanded","false")}));
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("visible");observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll(".reveal").forEach(el=>observer.observe(el));
